### ISSUE TITLE
Some info and issues

### ISSUE THREAD

**Issue by lfom** [arnarg/waybind#4]
Hello, there.

Thanks for this. It was the only thing that actually worked on Gnome + Wayland for me on Pop!_OS 20.10 (like Ubuntu 20.10). It seems that using `xbcomp` does not work on Wayland.

But I had some trouble making it work, so maybe these steps can help someone else:

First, create the group and user:
```
sudo groupadd --system uinput
sudo useradd -M -r -G uinput,input waybind
```

But creating the group and user as system ones didn't hide the user in Gnome, so I added a file **/var/lib/AccountsService/users/waybind** to hide it (just an annoyance):
```
[User]
XSession=
Icon=/var/lib/gdm3/.face
SystemAccount=true
```

Finally, I think something is wrong with the code that loads **config.yml**, it only works with **/etc/waybind/config.yml**. I had a file in my home folder and it did not work, maybe it has to be installed as an user unit instead of system? Checking the log when I was trying to make it work, it showed:
```
mar 10 11:20:46 systemd[1]: Started Waybind deamon service.
mar 10 11:20:46 waybind[5023]: Failed to find configuration /etc/waybind/config.yml
mar 10 11:20:46 waybind[5023]: Failed to find configuration /home/waybind/.config/waybind/config.yml
mar 10 11:20:46 waybind[5023]: Failed to find configuration ./config.yml
```
Also, checking the source, I was not sure if the local configuration file would override the system one or not.

And I dot know if it is expected or not, but the number of the device input event changes every boot, maybe this can be improved somehow. I am using an iMac12,1: event0 to event2 are power/sleep buttons, and the actual USB keyboard changes between event5 and event7 from what I have observed so far.

Thanks again. Regards.

**Comment by arnarg** [comment]
> Finally, I think something is wrong with the code that loads config.yml, it only works with /etc/waybind/config.yml. I had a file in my home folder and it did not work, maybe it has to be installed as an user unit instead of system?

It only looks in the running user's home directory. In order to for it to look for it in your home directory you would need to be running it as your user. And to be able to do that you would need to be in the `input` and `uinput` groups.

You can see from the logs that it is looking in `waybind`'s home foler.

> Also, checking the source, I was not sure if the local configuration file would override the system one or not.

The priority is `./config.yml`, `$HOME/.config/waybind/config.yml` and finally `/etc/waybind/config.yml`.

> And I dot know if it is expected or not, but the number of the device input event changes every boot, maybe this can be improved somehow.

Find your keyboard in `/dev/input/by-id` and that should be the same between reboots. These are symlinks to `/dev/input/eventX` so just do `ls -l /dev/input/by-id` to see which one is which.
